### PR TITLE
Remove Stream Wrapper Functionality

### LINKED ISSUE #28: Remove stream wrapper functionality
Fixes #23.

---

Originally posted by @mtymek at https://github.com/zendframework/zend-view/pull/34

### LINKED ISSUE #29: [v3] remove Zend\View\Stream and useStreamWrapper  option
If I don't misunderstood, zf1 Zend_View_Stream was introduced for short_open_tag off environment , 

but `Since PHP 5.4.0, <?= is always available.`
http://php.net/manual/en/ini.core.php#ini.short-open-tag

so I think Zend_View_Stream can be removed since zf3.

---

Originally posted by @sasezaki at https://github.com/zendframework/zend-view/issues/23

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| BC Break      | yes

### Description

Closes #29 
Closes #28 

Deprecated in #91

- Updates the path stack template resolver removing deprecated methods related to stream wrapper
- Removes the Stream wrapper class
- Updates psalm baseline

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
IMO OK, but CI didn't run at all now? 🤔

**Comment by gsteel** [comment]
It's weird. I forced pushed with a cs fix and nothing ran 🤷‍♂️

I think this time it was a GH thing. There's a failed run in the history.

**Comment by Ocramius** [comment]
Checking the CI run @ https://github.com/laminas/laminas-view/runs/5014074970?check_suite_focus=true#step:3:374 (not reported in here :shrug: )

```
Running ./vendor/bin/phpcs -q --report=checkstyle | cs2pr
Error: Type ini_get is not used in this file.
```

**Comment by gsteel** [comment]
Yes, CI ran fine - I spotted the CS violation, fixed, amended and force-pushed - then GH refused to re-run the matrix. Can you hit "Re-Run all jobs" there for me? I don't have permission to do that, or I can find something arbitrary to commit…

**Comment by Ocramius** [comment]
@gsteel I did re-trigger CI, but it only re-ran on the commit previous to your force-push.

Could you perhaps rebase and force-push, to trigger it from your end?

**Review by Ocramius — APPROVED** [review]
And now it did run, thanks @gsteel!

**Pull request merged**
