### PR TITLE
Fix psalm issues due to improved upstream types

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| QA            | yes

### Description

- Bump coding standard to 2.5
- Bump psalm to 5.4
- Update (some) locked deps

`laminas-console` is beginning to make it impossible to keep dependencies sane - Ignoring platform reqs is becoming more unsafe on PHP 8.0 for example.

Closes #192

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @gsteel!

**Comment by Ocramius** [comment]
> Error: Call to undefined function enum_exists()

Something wrong with latest PHPUnit dependencies, IMO 🤔

**Comment by Ocramius** [comment]
Merging here regardless: CI failure unrelated 👍

**Comment by gsteel** [comment]
Yes. There's another patch to explain the failure. Console needs to be dropped

**Comment by Ocramius** [comment]
Yup: ignoring platform requirements was the problem, thanks! 💪

**Pull request merged**
