### PR TITLE
Cache and Session packages are not used anywhere

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Neither `cache` nor `session` are referenced anywhere in `view`.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Most excellent, thanks @gsteel!

**Comment by Ocramius** [comment]
Hmm, lowest deps build is experiencing failures 🤔

Also, need to change default branch before merging (that's on me)

**Review by Ocramius — CHANGES_REQUESTED** [review]
We'll need to handle this one: 


```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Return type of Laminas\Session\Storage\AbstractSessionArrayStorage::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

No idea where it is pulling `laminas/laminas-session` from :|

**Comment by gsteel** [comment]
I think lowest deps is failing here because flash messenger requires session ^2.8.x but ^2.12 is required for 8.1

**Comment by Ocramius** [comment]
What we can do here then (possible alternatives):

 1. upgrade flash messenger to latest deps (separate patch) then upgrade flash messenger here
 2. introduce a `conflict` with older `laminas/laminas-session` versions

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @gsteel!

**Pull request merged**
