### PR TITLE
Removes all outdated polyfills for related components, dropped PHP 7.3 support

### PR DESCRIPTION
**Pull request by froschdesign**
|    Q          |   A
|-------------- | ------
| Enhancement | yes

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Comment by froschdesign** [comment]
@Ocramius 
Version 7.3 of PHP is a problem – _as to be expected_.

**Comment by Ocramius** [comment]
Let's drop it :fire:

**Comment by froschdesign** [comment]
Uff, this component is still using laminas-coding-standard with version 1. :weary:

**Comment by Ocramius** [comment]
@froschdesign I've rebased this, but won't be able to work on it today, so it will have to slide to `2.17.0`

**Comment by Ocramius** [comment]
A rebase is needed here

**Comment by gsteel** [comment]
Just tried dropping ^7 locally but we can't until `laminas-console` is removed _(In 3.0?)_ it would appear.

**Comment by Ocramius** [comment]
Rebased and adjusted baseline accordingly: :ship:

**Comment by Ocramius** [comment]
Thanks @froschdesign!

**Pull request merged**
