### PR TITLE
Prepare for Renovate with reusable workflows

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

### CODE REVIEW

**Comment by Ocramius** [comment]
@gsteel wdyt? This OK for `3.0.0`-only?

**Review by Ocramius — APPROVED** [review]

**Comment by gsteel** [comment]
@Ocramius - This is already in 2.20.x from #137 but it won't cause any conflicts merging up 2 would it (?) so why not. Maybe we could get 2.20 out the door? I still have more work to do on deprecations but there can be a 2.21+ right?

**Comment by Ocramius** [comment]
Changed base - rebase will be done by maintainers on merge :)

**Comment by Ocramius** [comment]
@gsteel I lack an overview of what's needed for `2.20.0` - if you want, I can cut a release, and let the rest slip into `2.21.0`

**Comment by gsteel** [comment]
A release would be great @Ocramius because once merged up into 3.x there's a load of pulls that can come in to target 3.x to deal with the deprecations introduced in 2.x

I think you misunderstood [my comment](https://github.com/laminas/laminas-view/pull/144#issuecomment-1046679026) - this pull is a duplicate of #137 - cutting a 2.20 release would make this pull obsolete. I just figured that merging _this_ pull into 3 would cause zero issues with a merge-up from 2.

**Comment by gsteel** [comment]
@Ocramius - The stuff needed for renovate is already merged into 2.20.x so this pull is obsolete once 2.20 is released. Also, there's nothing outstanding to prevent a 2.20 release as far as I can see that can't go into future minors. I can help with the merge up into 3.x if it's a pain in the ass.

**Comment by Ocramius** [comment]
Ah, sorry, that does indeed clear it up :) 

Thanks @ghostwriter and @gsteel!

**Pull request closed without merging**
