### PR TITLE
Use DI for the HtmlAttributes helper

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| BC Break      | no/maybe
| New Feature   | yes
| QA            | yes

### Description

The HTML Attributes helper was reaching into the view (which might not be there) in order to fetch a plugin (Escape helper), so that it could fetch an escaper instance from that plugin… and it was messy.

This pull adds a factory that injects an escaper into the helpers constructor and wires it up in the plugin manager.

This will aid in dealing with future changes to the shipped escape helpers.

It also deprecates the inheritance in the helper itself.

Not sure if this is considered BC breaking or not, theoretically, consumers will only interact with the helper by way of `$this->htmlAttributes()` and that works the same as before.

I could make the escaper nullable in the constructor and new one if preferred and then tighten things up further in 3 when we deal with the deprecations?

### CODE REVIEW

**Comment by gsteel** [comment]
Not sure why composer is refusing to install. This pull was branched from 2.21.x and is targeting it too 🤷‍♂️

Are we going to have to back-port the `pre-install.sh` to checkout 2.99.x before install?

**Comment by Ocramius** [comment]
I think this is because the branch is on a PR. The checkout may be needed until circular dependencies are gone :|

**Comment by gsteel** [comment]
Could we get #146 in `2.21.x` before looking at this one? This conflicts with #146 and I'd rather rebase this on that than the other way around!

**Comment by Ocramius** [comment]
@gsteel I had asked to split that one up - do you prefer to have it in there in one go?

**Comment by gsteel** [comment]
@Ocramius I already did split it up - the gravatar stuff went into #147

**Comment by gsteel** [comment]
So changes to the helper in #146 were nearly identical to this pull, so now, this is only the factory addition - also the constructor argument is reverted to be nullable, meaning it can be instantiated without the factory at all, therefore preserving BC

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks @gsteel!

**Pull request merged**
